version: "3.8"

services:
  chroma:
    container_name: chroma
    image: chromadb/chroma
    volumes:
      - chroma_data:/chroma
    restart: unless-stopped

  locations_recommend_system:
    container_name: locations_recommend_system
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 7860
    ports:
      - "83:7860"
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
    depends_on:
      - chroma
    restart: unless-stopped
volumes:
  chroma_data:
